global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using HomeAutomation.Data.Bl.Abstract;
global using ent = HomeAutomation.Data.Entities;
global using dto = HomeAutomation.Shared.Dtos;
global using flt = HomeAutomation.Shared.Filters;